/*
 * MDIO_cfg.h
 *
 *  Created on: Aug 29, 2019
 *      Author: maha_
 */

#ifndef MDIO_CFG_H_
#define MDIO_CFG_H_


#define MDIO_PORTA0_DIR   MDIO_OUTPUT
#define MDIO_PORTA1_DIR   MDIO_OUTPUT
#define MDIO_PORTA2_DIR   MDIO_OUTPUT
#define MDIO_PORTA3_DIR   MDIO_OUTPUT
#define MDIO_PORTA4_DIR   MDIO_OUTPUT
#define MDIO_PORTA5_DIR   MDIO_OUTPUT
#define MDIO_PORTA6_DIR   MDIO_OUTPUT
#define MDIO_PORTA7_DIR   MDIO_OUTPUT

#define MDIO_PORTB0_DIR   MDIO_OUTPUT
#define MDIO_PORTB1_DIR   MDIO_OUTPUT
#define MDIO_PORTB2_DIR   MDIO_OUTPUT
#define MDIO_PORTB3_DIR   MDIO_OUTPUT
#define MDIO_PORTB4_DIR   MDIO_OUTPUT
#define MDIO_PORTB5_DIR   MDIO_OUTPUT
#define MDIO_PORTB6_DIR   MDIO_OUTPUT
#define MDIO_PORTB7_DIR   MDIO_OUTPUT

#define MDIO_PORTC0_DIR    MDIO_INPUT
#define MDIO_PORTC1_DIR    MDIO_INPUT
#define MDIO_PORTC2_DIR    MDIO_INPUT
#define MDIO_PORTC3_DIR    MDIO_INPUT
#define MDIO_PORTC4_DIR    MDIO_INPUT
#define MDIO_PORTC5_DIR    MDIO_INPUT
#define MDIO_PORTC6_DIR    MDIO_INPUT
#define MDIO_PORTC7_DIR    MDIO_INPUT

#define MDIO_PORTD0_DIR   MDIO_OUTPUT
#define MDIO_PORTD1_DIR   MDIO_OUTPUT
#define MDIO_PORTD2_DIR   MDIO_OUTPUT
#define MDIO_PORTD3_DIR   MDIO_OUTPUT
#define MDIO_PORTD4_DIR   MDIO_OUTPUT
#define MDIO_PORTD5_DIR   MDIO_OUTPUT
#define MDIO_PORTD6_DIR   MDIO_OUTPUT
#define MDIO_PORTD7_DIR   MDIO_OUTPUT

/*PULL UP RESISTOR*/
#define MDIO_PORTC0_PULLUP   MDIO_HIGH
#define MDIO_PORTC1_PULLUP   MDIO_HIGH
#define MDIO_PORTC2_PULLUP   MDIO_HIGH
#define MDIO_PORTC3_PULLUP   MDIO_HIGH
#define MDIO_PORTC4_PULLUP   MDIO_HIGH
#define MDIO_PORTC5_PULLUP   MDIO_HIGH

#endif /* MDIO_CFG_H_ */
